name: Build on master push (amd64 only)

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build electrs image
    runs-on: ubuntu-22.04
    env:
      VERSION: v0.10.2
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            suffix=amd64
          tags: |
            type=ref,event=tag,priority=200
            type=ref,event=branch,priority=200
            type=sha,priority=100,prefix=sha-,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v3

      - name: Build and push the image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          build-args: 
            VERSION: ${{ env.VERSION }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}